# Generated by Django 6.0.6 on 2026-07-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopee', '0002_seed_chopee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, default=2026, null=True),
        ),
    ]
